repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1  # Updated to latest stable version that supports Python 3.12
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Specify version 5.12.0 or later
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Match installed version 1.15.0
    hooks:
      - id: mypy
        exclude: 'src/.*\.pyi$'
        args: ["src", "tests", "examples"]
        pass_filenames: false
        language: system