from fastapi import APIRouter
from sqlalchemy.orm import Session

router: APIRouter

def get_db() -> Session: ...
def initiate_oauth() -> object: ...
def oauth_callback(request: object, code: str, db: Session) -> dict: ...
def seller_info(merchant_id: str, db: Session) -> dict: ...
def get_square_merchant_info(oauth_token: str) -> dict: ...
def get_merchant_private_key(oauth_token: str, merchant_id: str) -> str | None: ...
def store_merchant_private_key(
    oauth_token: str, merchant_id: str, private_key: str
) -> None: ...
def get_or_generate_merchant_keys(oauth_token: str, merchant_id: str) -> object: ...
def populate_synvya_profile(merchant_data: dict, keys: object) -> object: ...
def fetch_and_prepare_profile(oauth_token: str) -> object: ...
